#!/bin/sh
set -e

for input in $(ls *.md)
do
    output=`echo $input|sed 's/\(.*\)md$/\1html/g'`
    if [ $input = 'manpage.md' ]
    then
        echo "Converting manual page"
        pandoc -T 'GladTeX - Generator For HTML With Embedded LaTeX Formulas' -s -f markdown -t html -o $output $input
    else
        echo "Converting $input"
        pandoc -c style.css -s -f markdown -t html -o $output $input
    fi
done
